In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder 
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv('covid_toy.csv')

In [4]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [5]:
from sklearn.model_selection import train_test_split 
X_train,X_test,y_train,y_train=train_test_split(df.drop(columns= ['has_covid']),df['has_covid'],test_size =0.2)

<h>Aam zindgi <h2/>

In [6]:
#forst we will apply imputer  for fill missing in fever 
si = SimpleImputer()
X_train_fever =si.fit_transform(X_train[['fever']])
X_test_fever =si.fit_transform(X_test[['fever']])
X_train_fever

array([[104.        ],
       [101.09722222],
       [101.09722222],
       [102.        ],
       [100.        ],
       [101.        ],
       [101.09722222],
       [101.09722222],
       [101.        ],
       [104.        ],
       [100.        ],
       [ 98.        ],
       [ 98.        ],
       [101.        ],
       [ 98.        ],
       [102.        ],
       [100.        ],
       [ 99.        ],
       [ 98.        ],
       [101.        ],
       [104.        ],
       [101.        ],
       [103.        ],
       [102.        ],
       [104.        ],
       [100.        ],
       [101.        ],
       [104.        ],
       [101.        ],
       [103.        ],
       [101.09722222],
       [101.09722222],
       [104.        ],
       [101.        ],
       [104.        ],
       [104.        ],
       [ 99.        ],
       [102.        ],
       [101.        ],
       [101.09722222],
       [ 98.        ],
       [ 98.        ],
       [100.        ],
       [ 98.        ],
       [ 98.        ],
       [101.        ],
       [103.        ],
       [102.        ],
       [103.        ],
       [102.        ],
       [ 99.        ],
       [100.        ],
       [103.        ],
       [100.        ],
       [103.        ],
       [ 98.        ],
       [101.        ],
       [104.        ],
       [101.        ],
       [101.        ],
       [100.        ],
       [103.        ],
       [100.        ],
       [104.        ],
       [100.        ],
       [ 99.        ],
       [ 99.        ],
       [ 98.        ],
       [104.        ],
       [101.09722222],
       [103.        ],
       [104.        ],
       [103.        ],
       [102.        ],
       [101.        ],
       [100.        ],
       [101.        ],
       [100.        ],
       [ 98.        ],
       [102.        ]])

In [7]:
X_train

    age  gender  fever   cough       city
86   25    Male  104.0    Mild  Bangalore
10   75  Female    NaN    Mild      Delhi
25   23    Male    NaN    Mild     Mumbai
75    5    Male  102.0    Mild    Kolkata
76   80    Male  100.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
51   11  Female  100.0  Strong    Kolkata
70   68  Female  101.0  Strong      Delhi
88    5  Female  100.0    Mild    Kolkata
17   40  Female   98.0  Strong      Delhi
27   33  Female  102.0  Strong      Delhi

[80 rows x 5 columns]

In [8]:
# nowwill do Ordinal enoding 
oe =OrdinalEncoder(categories = [['Mild','Strong']])
X_train_cough =oe.fit_transform(X_train[['cough']])
X_test_cough =oe.fit_transform(X_test[['cough']])

In [9]:
#now we use OneHotEncoder 
ohe = OneHotEncoder(drop='first',sparse_output=False)
X_tain_gender_city =ohe.fit_transform(X_train[['gender','city']])
X_test_gender_city =ohe.fit_transform(X_test[['gender','city']])
X_tain_gender_city.shape

(80, 4)

In [10]:
X_train_age =X_train.drop(columns=['gender','fever','cough','city']).values
X_test_age =X_test.drop(columns=['gender','fever','cough','city']).values
X_train_age.shape

(80, 1)

X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender,X_train_cough))
X_test_transformed =  np.concatenate((X_test_age,X_test_fever,X_test_gender,X_test_cough))

In [11]:
X_train_cough
X_test_transformed

NameError: name 'X_test_transformed' is not defined

<h2>Mentos Zinndgi <h2/>

In [ ]:
from sklearn.compose import ColumnTransformer
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEnoder(categories = [['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(drop ='first',sparse_ouput = False),['gender','city'])
],remainder='passsthrough')

In [12]:
transformer.fit_transform(X_train)

NameError: name 'transformer' is not defined