In [1]:
# here we will understand Binning and Binarization | Discretization | Quantile Binning | KMeans Binning

In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as mlt

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score 
from sklearn.model_selection import cross_val_score

from sklearn.preprocessing import KBinsDiscretizer
from sklearn.compose import ColumnTransformer

In [4]:
df = pd.read_csv('train(ML).csv',usecols=['Age','Fare','Survived'])

In [5]:
df.dropna(inplace=True)

In [6]:

df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [7]:
x =df.iloc[:,1:3]
y= df.iloc[:,0]

In [8]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [9]:
clf =DecisionTreeClassifier()

In [10]:
clf.fit(x_train,y_train)
y_pred =clf.predict(x_test)

In [11]:
accuracy_score(y_test,y_pred)

0.6293706293706294

In [12]:
np.mean(cross_val_score(DecisionTreeClassifier(),x,y,cv=10,scoring='accuracy'))

np.float64(0.6387323943661971)

In [13]:
#now lets check with discretizer
kbins_age = KBinsDiscretizer(n_bins=5,encode='ordinal',strategy='quantile') 
bbins_fare = KBinsDiscretizer(n_bins=5,encode='ordinal',strategy='quantile')

In [14]:
trf =ColumnTransformer([
    ('first',kbins_age,[0]),
    ('second',bbins_fare,[1])
])

In [15]:
x_trans= trf.fit_transform(x_train)
x_test_trf = trf.transform(x_test)

C:\Users\Vishal\AppData\Roaming\Python\Python313\site-packages\sklearn\preprocessing\_discretization.py:296: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(
C:\Users\Vishal\AppData\Roaming\Python\Python313\site-packages\sklearn\preprocessing\_discretization.py:296: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(

In [16]:
trf.named_transformers_['second'].n_bins_

array([5])

In [17]:
trf.named_transformers_['second'].bin_edges_

array([array([  0.    ,   7.8958,  13.    ,  26.    ,  51.4792, 512.3292])],
      dtype=object)

In [18]:
output = pd.DataFrame({
    'age':x_train['Age'],
    'age_trf':x_trans[:,0],
    'fare':x_train['Fare'],
    'fare_trf':x_trans[:,1]
})

In [19]:
output['age_labels'] = pd.cut(x=x_train['Age'],
                            bins=trf.named_transformers_['first'].bin_edges_[0].tolist())
output['fare_labels'] = pd.cut(x=x_train['Fare'],
                            bins=trf.named_transformers_['second'].bin_edges_[0].tolist())

In [20]:
output.sample(5)

       age  age_trf     fare  fare_trf    age_labels   fare_labels
651  18.00      0.0  23.0000       2.0  (0.42, 19.0]  (13.0, 26.0]
644   0.75      0.0  19.2583       2.0  (0.42, 19.0]  (13.0, 26.0]
437  24.00      1.0  18.7500       2.0  (19.0, 25.0]  (13.0, 26.0]
489   9.00      0.0  15.9000       2.0  (0.42, 19.0]  (13.0, 26.0]
294  24.00      1.0   7.8958       1.0  (19.0, 25.0]  (0.0, 7.896]

In [21]:
clf =DecisionTreeClassifier()
clf.fit(x_trans,y_train)
y_pred2 =clf.predict(x_test_trf)

In [22]:
accuracy_score(y_test,y_pred2)

0.6433566433566433

In [ ]:
def discretize(bins,strategy):
    kbins_age = KBinsDiscretizer(n_bins=bins,encode='ordinal',strategy =strategy)
    kbins_fare = KBinsDiscretizer(n_bins=bins,encode='ordinal',strategy =strategy)

    trf ColumnTransformer([
        ('first':kbins_age,[0]),
        ('second':kbins_fare,[1])
    ])

    x_trf = trf.fit_transformer(x)
    print(np.mean(cross_val_score(DecisioTreeClassifier()x,y,vc=10,scoring='accuracy')))

    plt.figure(figsize = (14,4))
    plt.subplot(121)
    plt.hist(x['Age'])
    plt.title("before")

    plt.subplot(122)
    plt.hist(x_trf[''])