In [1]:
import pandas as pd

#working with JSON

In [3]:
pd.read_json('ML(DS).json')

                                               recipes
0    {'cuisine': 'Indian', 'dish': 'Biryani', 'ingr...
1    {'cuisine': 'Indian', 'dish': 'Butter Chicken'...
2    {'cuisine': 'Indian', 'dish': 'Palak Paneer', ...
3    {'cuisine': 'Indian', 'dish': 'Chole Bhature',...
4    {'cuisine': 'Indian', 'dish': 'Masala Dosa', '...
..                                                 ...
114  {'cuisine': 'Moroccan', 'dish': 'Harira', 'ing...
115  {'cuisine': 'Moroccan', 'dish': 'Pastilla', 'i...
116  {'cuisine': 'Moroccan', 'dish': 'Zaalouk', 'in...
117  {'cuisine': 'Moroccan', 'dish': 'Kefta', 'ingr...
118  {'cuisine': 'Moroccan', 'dish': 'Msemmen', 'in...

[119 rows x 1 columns]

In [4]:
#we can get dataframe forom through URL we have just write pd.read_json('URL')

#working with SQL

In [8]:
pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
     -- ------------------------------------- 0.8/11.9 MB 1.5 MB/s eta 0:00:08
     --- ------------------------------------ 1.0/11.9 MB 1.7 MB/s eta 0:00:07
     ----- ---------------------------------- 1.6/11.9 MB 1.8 MB/s eta 0:00:06
     ------- -------------------------------- 2.1/11.9 MB 1.9 MB/s eta 0:00:06
     -------- ------------------------------- 2.6/11.9 MB 2.0 MB/s eta 0:00:05
     ---------- ----------------------------- 3.1/11.9 MB 2.0 MB/s eta 0:00:05
     ------------ --------------------------- 3.7/11.9 MB 2.1 MB/s eta 0:00:04
     ------------- -------------------------- 3.9/11.9 MB 2.1 MB/s eta 0:00:04
     --------------- ------------------------ 4.5/11.9 MB 2.0 MB/s eta 0:00:04
     ---------------- ----------------------- 5.0/11.9 MB 2.0 MB/s eta 0:00:04
     ----------------- ---------------------- 5.2/11.9 MB 2.0 MB/s eta 0:00:04
     ------------------ --------------------- 5.5/11.9 MB 2.0 MB/s eta 0:00:04
     --------------------- ------------------ 6.3/11.9 MB 2.0 MB/s eta 0:00:03
     ---------------------- ----------------- 6.6/11.9 MB 2.0 MB/s eta 0:00:03
     ----------------------- ---------------- 7.1/11.9 MB 2.0 MB/s eta 0:00:03
     ------------------------- -------------- 7.6/11.9 MB 2.0 MB/s eta 0:00:03
     -------------------------- ------------- 7.9/11.9 MB 2.0 MB/s eta 0:00:02
     ---------------------------- ----------- 8.4/11.9 MB 2.0 MB/s eta 0:00:02
     ------------------------------ --------- 8.9/11.9 MB 2.0 MB/s eta 0:00:02
     ------------------------------ --------- 9.2/11.9 MB 2.1 MB/s eta 0:00:02
     -------------------------------- ------- 9.7/11.9 MB 2.0 MB/s eta 0:00:02
     ---------------------------------- ----- 10.2/11.9 MB 2.0 MB/s eta 0:00:01
     ----------------------------------- ---- 10.5/11.9 MB 2.0 MB/s eta 0:00:01
     ------------------------------------- -- 11.0/11.9 MB 2.0 MB/s eta 0:00:01
     -------------------------------------- - 11.5/11.9 MB 2.0 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 2.0 MB/s  0:00:06
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml): started
  Building wheel for mysql.connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp313-cp313-win_amd64.whl size=248051 sha256=b5880f0043024904820bd67aa349aa6a66707b6f7b0c33d67de39e15c50b54c5
  Stored in directory: c:\users\vishal\appdata\local\pip\cache\wheels\4e\c1\23\9423c444a75266a05275c80ebf5c6efe2368388e976b690a0f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9
Note: you may need to restart the kernel to use updated packages.

In [10]:
import mysql.connector

In [16]:
con = mysql.connector.connect(host='localhost',user='root',password='',database='world')

In [18]:
pd.read_sql_query("SELECT*FROM city WHERE CountryCode LIKE 'IND'",con)

C:\Users\Vishal\AppData\Local\Temp\ipykernel_24820\26934223.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT*FROM city WHERE CountryCode LIKE 'IND'",con)

       ID                Name CountryCode        District  Population
0    1024     Mumbai (Bombay)         IND     Maharashtra    10500000
1    1025               Delhi         IND           Delhi     7206704
2    1026  Calcutta [Kolkata]         IND    West Bengali     4399819
3    1027    Chennai (Madras)         IND      Tamil Nadu     3841396
4    1028           Hyderabad         IND  Andhra Pradesh     2964638
..    ...                 ...         ...             ...         ...
336  1360        Ambala Sadar         IND         Haryana       90712
337  1361          Baidyabati         IND    West Bengali       90601
338  1362               Morvi         IND         Gujarat       90357
339  1363             Raigarh         IND     Chhatisgarh       89166
340  1364            Vejalpur         IND         Gujarat       89053

[341 rows x 5 columns]