In [6]:
import pandas  as pd 
import numpy as np  
import re 
import matplotlib.pyplot as plt 

%matplotlib inline

In [8]:
data_path = 'smartwatches.csv'
df = pd.read_csv(data_path)
df.drop_duplicates(inplace = True)
train_df =df.sample(frac = 0.8,random_state =42)
test_df = df.drop(train_df.index)
train_df = train_df.reset_index()
test_df = test_df.reset_index()

In [10]:
df.shape ,train_df.shape,test_df.shape

((450, 16), (360, 17), (90, 17))

In [11]:
train_df.head()

,index,Unnamed: 0,Brand,Current Price,Original Price,Discount Percentage,Rating,Number OF Ratings,Model Name,Dial Shape,Strap Color,Strap Material,Touchscreen,Battery Life (Days),Bluetooth,Display Size,Weight
0,407,407,zebronics,2949.0,4199.0,29.768993,3.1,10.0,LEATHER fit-650,Oval,Black,Leather,Yes,NaN,Yes,2.7 inches,NaN
1,444,444,fire-boltt,6999.0,15999.0,56.253516,2.6,NaN,bsw020,Circle,Brown,Silicon,Yes,8.0,Yes,1.4 inches,NaN
2,117,117,fire-boltt,2499.0,11999.0,79.173264,4.1,1990.0,BSW070,NaN,NaN,NaN,Yes,8.0,Yes,1.9 inches,75g +
3,30,30,boat,1999.0,7990.0,74.981227,3.6,827.0,NaN,NaN,NaN,NaN,NaN,8.0,Yes,NaN,75g +
4,415,415,fire-boltt,2299.0,5999.0,61.676946,2.5,24.0,NINJA PRO MAX,Square,Blue,Silicon,Yes,22.0,Yes,1.6 inches,NaN

In [12]:
train_df.drop(['index','Unnamed: 0'],axis=1,inplace=True)

In [13]:
train_df.head()

,Brand,Current Price,Original Price,Discount Percentage,Rating,Number OF Ratings,Model Name,Dial Shape,Strap Color,Strap Material,Touchscreen,Battery Life (Days),Bluetooth,Display Size,Weight
0,zebronics,2949.0,4199.0,29.768993,3.1,10.0,LEATHER fit-650,Oval,Black,Leather,Yes,NaN,Yes,2.7 inches,NaN
1,fire-boltt,6999.0,15999.0,56.253516,2.6,NaN,bsw020,Circle,Brown,Silicon,Yes,8.0,Yes,1.4 inches,NaN
2,fire-boltt,2499.0,11999.0,79.173264,4.1,1990.0,BSW070,NaN,NaN,NaN,Yes,8.0,Yes,1.9 inches,75g +
3,boat,1999.0,7990.0,74.981227,3.6,827.0,NaN,NaN,NaN,NaN,NaN,8.0,Yes,NaN,75g +
4,fire-boltt,2299.0,5999.0,61.676946,2.5,24.0,NINJA PRO MAX,Square,Blue,Silicon,Yes,22.0,Yes,1.6 inches,NaN

In [14]:
train_df['Display Size'].isna().sum()

np.int64(27)

In [15]:
train_df['Display Size'].value_counts()

Display Size
1.7 inches     56
1.3 inches     50
1.8 inches     48
1.4 inches     35
0.1 inches     28
1.6 inches     25
1.9 inches     21
1.2 inches     17
1.1 inches      6
1.5 inches      6
0.2 inches      6
4.3 inches      4
0.9 inches      4
2.7 inches      2
4.4 inches      2
4.5 inches      2
3.3 inches      2
2.0 inches      2
1.0 inches      2
2.3 inches      1
35.9 inches     1
18.5 inches     1
0.0 inches      1
27.9 inches     1
3.0 inches      1
4.0 inches      1
2.1 inches      1
6.9 inches      1
2.4 inches      1
15.9 inches     1
3.5 inches      1
0.6 inches      1
0.5 inches      1
20.0 inches     1
Name: count, dtype: int64

In [16]:
 train_df['Display Size'].fillna('0.0inches',inplace = True)

C:\Users\Vishal\AppData\Local\Temp\ipykernel_10068\3380192022.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train_df['Display Size'].fillna('0.0inches',inplace = True)

In [18]:
train_df['Display Size'].isna().sum()

np.int64(0)

In [20]:
'0.0 inches'.split()

['0.0', 'inches']

In [24]:
train_df['Display Size'] = train_df['Display Size'].apply(lambda x: float(x.split()[0]))

ValueError: could not convert string to float: '0.0inches'